name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Validate the Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3.4.2

  build:
    needs: validation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: [21]

    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bookstoretest
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:${{ job.services.mysql.ports[3306] }}/bookstoretest

      - name: Run tests with Testcontainers
        run: ./gradlew test --parallel || ./gradlew test --parallel || ./gradlew test --parallel
        env:
          SPRING_DATASOURCE_URL: jdbc:tc:mysql:8.0:///bookstoretest

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/test-results/test